# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function for computing forward probabilities
#'
#' @name forward
#' @title function for computing forward probabilities
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return A NxT matrix of forward probabilities
forward <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_forward', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' function for computing forward probabilities (log scale)
#'
#' @name forward_log
#' @title function for computing forward probabilities (log scale)
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return A NxT matrix of forward probabilities
forward_log <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_forward_log', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' function for computing backward probabilities
#'
#' @name backward
#' @title function for computing backward probabilities
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return A NxT matrix of backward probabilities
backward <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_backward', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' function for computing backward probabilities (log scale)
#'
#' @name backward_log
#' @title function for computing backward probabilities (log scale)
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return A NxT matrix of backward probabilities
backward_log <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_backward_log', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' function for computing gamma values
#'
#' @name gamma
#' @title function for computing gamma values
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return A NxT matrix of gamma
gamma <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_gamma', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' function for computing gamma values
#'
#' @name gamma_old
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return A NxT matrix of backward probabilities
gamma_old <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_gamma_old', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' function for computing xi matrices
#'
#' @name xi
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return A NxNxT tensor of xi values
xi <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_xi', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' function for computing updated HMM parameters
#'
#' @name update_parameters
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return list with updated parameters
update_parameters <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_update_parameters', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' @name forward_algorithm
#' @title Forward algorithm for likelihood computation
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return Model likelihood for given data
forward_algorithm <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call('_andyHMM_forward_algorithm', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_matrix, observations)
}

#' @name viterbi_
#' @title Viterbi algorithm
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_probabilities NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return most likely sequence of hidden states
viterbi <- function(initial_probs, transition_matrix, emission_probabilities, observations) {
    .Call('_andyHMM_viterbi', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_probabilities, observations)
}

#' @name viterbi_log
#' @title Viterbi algorithm (Logarithm's version)
#' @param initial_probs 1xN vector of initial probabilities 
#' @param transition_matrix NxN matrix of hidden state transition probabilities 
#' @param emission_probabilities NxK matrix of emission probabilities 
#' @param observations vector of observed variable observations
#' @return most likely sequence of hidden states
viterbi_log <- function(initial_probs, transition_matrix, emission_probabilities, observations) {
    .Call('_andyHMM_viterbi_log', PACKAGE = 'andyHMM', initial_probs, transition_matrix, emission_probabilities, observations)
}

