# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function for computing updated HMM parameters
#'
#' @name update_parameters
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return list with updated parameters
#' @export
update_parameters <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call(`_andyHMM_update_parameters`, initial_probs, transition_matrix, emission_matrix, observations)
}

#' @name forward_algorithm
#' @title Forward algorithm for likelihood computation
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_matrix NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return Model likelihood for given data
#' @export
forward_algorithm <- function(initial_probs, transition_matrix, emission_matrix, observations) {
    .Call(`_andyHMM_forward_algorithm`, initial_probs, transition_matrix, emission_matrix, observations)
}

#' @name viterbi
#' @title Viterbi algorithm
#' @param initial_probs 1xN vector of initial probabilities
#' @param transition_matrix NxN matrix of hidden state transition probabilities
#' @param emission_probabilities NxK matrix of emission probabilities
#' @param observations vector of observed variable observations
#' @return most likely sequence of hidden states
#' @export
viterbi <- function(initial_probs, transition_matrix, emission_probabilities, observations) {
    .Call(`_andyHMM_viterbi`, initial_probs, transition_matrix, emission_probabilities, observations)
}

#' @name viterbi_log
#' @title Viterbi algorithm (Logarithm's version)
#' @param initial_probs 1xN vector of initial probabilities 
#' @param transition_matrix NxN matrix of hidden state transition probabilities 
#' @param emission_probabilities NxK matrix of emission probabilities 
#' @param observations vector of observed variable observations
#' @return most likely sequence of hidden states
#' @export
viterbi_log <- function(initial_probs, transition_matrix, emission_probabilities, observations) {
    .Call(`_andyHMM_viterbi_log`, initial_probs, transition_matrix, emission_probabilities, observations)
}

